# Generated by Django 4.1.7 on 2023-03-14 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyisim')),
                ('bio', models.TextField(max_length=500, verbose_name='hakkımda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('follow', models.ManyToManyField(blank=True, to='user.profile', verbose_name='Takip')),
                ('followers', models.ManyToManyField(blank=True, to='user.profile', verbose_name='Takipçi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
