# Generated by Django 4.1.7 on 2023-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profiles/defaultt pp.jpeg', null=True, upload_to='profiles/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Merhaba Ben Bir Blog Yazarıyım.', max_length=500, verbose_name='hakkımda'),
        ),
    ]
